-- All fixtures and changes are rolled back. Run only in isolated staging.
begin;
set local request.jwt.claims='{"role":"service_role"}';
set local role service_role;
do $$
declare a uuid; b uuid; p uuid:=gen_random_uuid(); pb uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); cb uuid:=gen_random_uuid(); sale uuid:=gen_random_uuid(); r jsonb;
begin
 r:=public.v16_store_action('v16-test-a','a@example.invalid','create','{"name":"Test A","slug":"v16-test-store-a","requested_plan":"gestion","consent":true}');
 assert r->>'ok'='true','creation failed'; a:=(r->'store'->>'id')::uuid;
 assert r->'store'->>'status'='pending' and r->'store'->>'plan'='tienda','signup self-activated';
 r:=public.v16_store_action('v16-test-b','b@example.invalid','create','{"name":"Test B","slug":"v16-test-store-b","requested_plan":"gestion","consent":true}');b:=(r->'store'->>'id')::uuid;
 assert public.v16_store_action('v16-test-a','a@example.invalid','owner_list')->>'error'='forbidden','subscriber saw owner registry';
 assert public.v16_store_action('v16-test-a','a@example.invalid','owner_store',jsonb_build_object('store_id',a,'plan','gestion','status','active'))->>'error'='forbidden','subscriber self-granted CRM';
 assert public.v16_store_action('v16-test-a','a@example.invalid','brand','{"name":"A","primary_color":"#123456","accent_color":"#ff7920","whatsapp":"","published":true}')->>'error'='inactive','pending store changed';
 assert public.v16_store_action('v16-test-owner','Max.huracan73@gmail.com','owner_store',jsonb_build_object('store_id',a,'plan','tienda','status','active'))->>'ok'='true','owner could not activate';
 assert public.v16_store_action('v16-test-owner','Max.huracan73@gmail.com','owner_store',jsonb_build_object('store_id',b,'plan','gestion','status','active'))->>'ok'='true';
 assert public.v16_store_action('v16-test-a','a@example.invalid','customer',jsonb_build_object('id',c,'name','Client A','phone','','notes',''))->>'error'='locked','Tienda granted CRM';
 assert public.v16_store_action('v16-test-a','a@example.invalid','financing','{"financing":{"2":15,"4":55,"6":78}}')->>'error'='locked','Tienda granted calculator';
 r:=public.v16_store_action('v16-test-a','a@example.invalid','product',jsonb_build_object('id',p,'name','Test Product A','cash_price',1000.01,'visible',true,'features',jsonb_build_array('Potencia 1800 W'),'specifications',jsonb_build_object('Potencia','1800 W')));assert r->>'ok'='true';
 r:=public.v16_store_action('v16-test-b','b@example.invalid','product',jsonb_build_object('id',pb,'name','Test Product B','cash_price',2000,'visible',true,'features','[]'::jsonb,'specifications','{}'::jsonb));assert r->>'ok'='true';
 assert public.v16_store_action('v16-test-b','b@example.invalid','product',jsonb_build_object('id',p,'name','Hacked','cash_price',1,'visible',true,'features','[]'::jsonb,'specifications','{}'::jsonb))->>'error'='forbidden','cross-tenant update';
 r:=public.v16_store_action('v16-test-a','a@example.invalid','workspace');
 assert jsonb_array_length(r->'products')=1 and r->'products'->0->>'name'='Test Product A','workspace leaked other store';
 assert r->'store'->>'owner_site_user_id'='v16-test-a','wrong owner';
 assert public.v16_public_store('v16-test-store-a')is null,'unpublished store leaked';
 assert public.v16_store_action('v16-test-a','a@example.invalid','brand','{"name":"Test A","primary_color":"#123456","accent_color":"#ff7920","whatsapp":"5491100000000","published":true}')->>'ok'='true';
 r:=public.v16_public_store('v16-test-store-a');
 assert not(r->'store' ? 'owner_email')and not(r ? 'customers')and not(r ? 'sales'),'public projection leaked private fields';
 assert jsonb_array_length(r->'products')=1,'public catalog wrong';
 assert r->'store'->'financing'='{}'::jsonb,'cash tier leaked financing';
 insert into public.v16_store_products(id,store_id,name,cash_price) select gen_random_uuid(),a,'Limit fixture',100 from generate_series(1,49);
 assert public.v16_store_action('v16-test-a','a@example.invalid','product',jsonb_build_object('id',gen_random_uuid(),'name','Over limit','cash_price',1,'visible',true,'features','[]'::jsonb,'specifications','{}'::jsonb))->>'error'='limit','product limit bypass';
 assert public.v16_store_action('v16-test-a','a@example.invalid','request_plan','{"requested_plan":"gestion"}')->>'ok'='true';
 assert public.v16_store_action('v16-test-a','a@example.invalid','identity')->'store'->>'plan'='tienda','request changed active plan';
 assert public.v16_store_action('v16-test-owner','Max.huracan73@gmail.com','owner_store',jsonb_build_object('store_id',a,'plan','gestion','status','active'))->>'ok'='true';
 assert public.v16_store_action('v16-test-a','a@example.invalid','customer',jsonb_build_object('id',c,'name','Client A','phone','1100000000','notes','Own customer'))->>'ok'='true';
 assert public.v16_store_action('v16-test-b','b@example.invalid','customer',jsonb_build_object('id',cb,'name','Client B','phone','','notes',''))->>'ok'='true';
 assert public.v16_store_action('v16-test-b','b@example.invalid','customer',jsonb_build_object('id',c,'name','Hacked customer','phone','','notes',''))->>'error'='forbidden';
 assert public.v16_store_action('v16-test-a','a@example.invalid','sale',jsonb_build_object('id',sale,'customer_id',cb,'product_id',p))->>'error'='not_found','cross-tenant customer sale';
 assert public.v16_store_action('v16-test-a','a@example.invalid','sale',jsonb_build_object('id',sale,'customer_id',c,'product_id',pb))->>'error'='not_found','cross-tenant product sale';
 assert public.v16_store_action('v16-test-a','a@example.invalid','sale',jsonb_build_object('id',sale,'customer_id',c,'product_id',p))->>'ok'='true';
 assert public.v16_store_action('v16-test-a','a@example.invalid','sale',jsonb_build_object('id',sale,'customer_id',c,'product_id',p))->>'ok'='true';
 r:=public.v16_store_action('v16-test-a','a@example.invalid','workspace');
 assert jsonb_array_length(r->'sales')=1,'retry duplicated sale';assert(r->'sales'->0->>'total')::numeric=1000.01,'sale did not use server price';
 r:=public.v16_store_action('v16-test-b','b@example.invalid','workspace');assert jsonb_array_length(r->'sales')=0 and jsonb_array_length(r->'customers')=1,'CRM crossed tenants';
 assert public.v16_store_action('v16-test-a','a@example.invalid','financing','{"financing":{"2":15,"4":55,"6":78}}')->>'ok'='true';
 assert public.v16_public_store_asset(a,gen_random_uuid())=false,'unreferenced photo exposed';
 assert public.v16_store_action('v16-test-owner','Max.huracan73@gmail.com','owner_store',jsonb_build_object('store_id',a,'plan','tienda','status','active'))->>'ok'='true';
 r:=public.v16_store_action('v16-test-a','a@example.invalid','workspace');assert jsonb_array_length(r->'customers')=0 and jsonb_array_length(r->'sales')=0,'downgrade still exposed CRM';
 assert public.v16_store_action('v16-test-a','a@example.invalid','sale',jsonb_build_object('id',gen_random_uuid(),'customer_id',c,'product_id',p))->>'error'='locked';
 assert public.v16_store_action('v16-test-owner','Max.huracan73@gmail.com','owner_store',jsonb_build_object('store_id',a,'plan','tienda','status','paused'))->>'ok'='true';
 assert public.v16_public_store('v16-test-store-a')is null,'paused store public';
 assert public.v16_store_action('v16-test-a','a@example.invalid','asset',jsonb_build_object('kind','logo','asset_id',gen_random_uuid(),'reviewed',true))->>'error'='inactive','paused store accepted asset';
end $$;
rollback;
select 'PASS: tenant separation, pending/paused access, plan gates, public projection, limits, idempotent sales and immutable server totals' as result;
