"use client";
import {useEffect,useState} from "react";
import {PLANS,type Store,type PlanPrice} from "@/lib/subscriptions/plans";
import {PlanCards,changeStore,errorMessage} from "./plan-cards";
import {PlanValueEditor} from "./plan-value-editor";
export function OwnerSubscriptions(){
 const [data,setData]=useState<{stores:Store[];plans:PlanPrice[]}|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function refresh(){const response=await fetch("/api/v16/stores?view=owner",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(errorMessage(value.error));setData(value)}
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message))},[]);
 async function save(action:string,payload:unknown){setBusy(true);setMessage("");try{await changeStore(action,payload);await refresh();setMessage("Cambio guardado.")}catch(e){setMessage(e instanceof Error?e.message:"No se guardó.")}finally{setBusy(false)}}
 return <><section className="store-panel"><h2>Escala de valores y herramientas</h2><p>La tienda base es gratis. Después se suman herramientas pagas, gestión avanzada y acompañamiento uno a uno. El CRM se habilita por nivel, con autorización de Propietarios.</p><PlanCards prices={data?.plans}/><p>El logo, los colores y las fotos manuales están incluidos en Tienda gratis. Premium ofrece intervención humana y personalizada: a mayor dedicación de Amarango, mayor valor del servicio. Equipos, cobranzas y automatizaciones adicionales se incorporan en etapas posteriores.</p><details><summary>Definir valores, herramientas y promociones</summary><p>Tienda gratis conserva cuota mensual y alta sin costo. Los valores pagos siguen “A definir” hasta que Propietarios los cargue. Sólo Propietarios puede editar estos valores; guardar no genera cobros. En Premium, acordá el alcance y la dedicación del servicio uno a uno.</p><p role="status">{message}</p>{PLANS.filter(p=>p.id!=="tienda").map(p=>{const price=data?.plans.find(x=>x.id===p.id);return <PlanValueEditor key={p.id+JSON.stringify(price)} plan={p.id as "cuotas"|"gestion"|"premium"} price={price} disabled={busy||!data} onSave={payload=>save("owner_price",payload)}/>})}</details></section><section className="store-panel" id="suscriptores"><h2>Tiendas de suscriptores</h2><p>Habilitá la tienda gratis y autorizá los cambios de nivel cuando el negocio necesite más herramientas. Para Premium, acordá el alcance del servicio uno a uno. Pausar conserva los datos y oculta la tienda.</p><p role="status">{message}</p>{!data?<p>Cargando suscriptores…</p>:!data.stores.length?<p>Todavía no hay tiendas solicitadas. <a href="/suscribirme">Abrir el alta de una tienda</a>.</p>:<div className="store-list">{data.stores.map(s=><article key={s.id}><h3>{s.name}</h3><p>{s.owner_email} · /tienda/{s.slug}</p><p>Estado: {s.status==="active"?"Activa":s.status==="pending"?"Pendiente":"Pausada"} · Nivel actual: {PLANS.find(p=>p.id===s.plan)?.name} · Solicitado: {PLANS.find(p=>p.id===s.requested_plan)?.name}</p><form className="store-fields" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save("owner_store",{store_id:s.id,plan:f.get("plan"),status:f.get("status")})}}><label>Nivel a habilitar<select name="plan" defaultValue={s.status==="pending"?s.requested_plan:s.plan}>{PLANS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Estado<select name="status" defaultValue={s.status}><option value="pending">Pendiente</option><option value="active">Activa</option><option value="paused">Pausada</option></select></label><button disabled={busy}>Guardar habilitación</button></form></article>)}</div>}</section></>
}
