"use client";
import {PLANS,money,type PlanId,type PlanPrice} from "@/lib/subscriptions/plans";
import {planValue} from "@/lib/subscriptions/guidance";
export function PlanCards({prices=[],selected,onChoose,disabled=false}:{prices?:PlanPrice[];selected?:PlanId;onChoose?:(id:PlanId)=>void;disabled?:boolean}){
 return <div className="subscription-plans">{PLANS.map(p=>{const price=prices.find(x=>x.id===p.id),v=planValue(price);return <article key={p.id} className={`${selected===p.id?"selected ":""}${p.id==="premium"?"premium-plan":""}`}><small>{p.id==="tienda"?"EMPEZÁ GRATIS":p.id==="premium"?"ACOMPAÑAMIENTO DE MAYOR VALOR":`NIVEL ${p.order} · HERRAMIENTAS PAGAS`}</small><h3>{p.name}</h3><p>{p.headline}</p>{p.id==="tienda"?<><strong>Gratis</strong><span>Empezá sin inversión inicial.</span><span>Sin cuota mensual ni costo de alta.</span></>:<><strong>{v.current==null?"A definir":`${v.promotionActive&&price?.promo_price!=null?"Hoy: ":""}${money(v.current)} / mes`}</strong>{price?.setup_price!=null&&<span>{p.id==="premium"?"Implementación":"Alta"}: {money(price.setup_price)}</span>}</>}<ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul>{p.id!=="tienda"&&<div className="plan-value-breakdown">{v.tools.length>0&&<><small>{p.id==="premium"?"VALOR ESTIMADO DEL SERVICIO":"VALOR INDIVIDUAL DE REFERENCIA"}</small>{v.tools.map((t,i)=>{const promo=v.promotionActive&&t.promo_price!=null&&t.reference_price!=null&&t.promo_price<t.reference_price;return <div className="plan-tool-value" key={i}><span>{t.name}</span><span>{promo?<><del>{money(t.reference_price!)}</del> → <b>{money(t.promo_price!)}</b></>:t.reference_price==null?"A definir":money(t.reference_price)}</span></div>})}</>}<p>{p.id==="premium"?"Valor estimado del servicio":"Valor de las herramientas"}: <b>{v.referenceTotal==null?"A definir":money(v.referenceTotal)}</b></p>{v.previous!=null&&<p>Antes: <del>{money(v.previous)} / mes</del></p>}<p>{v.promotionActive&&price?.promo_price!=null?"Hoy":"Nivel completo"}: <b>{v.current==null?"A definir":`${money(v.current)} / mes`}</b></p>{v.promotionActive&&price?.promo_text&&<p className="plan-promo">{price.promo_text}</p>}{v.promotionActive&&price?.promo_expires_at&&<small>Vigencia hasta {new Date(price.promo_expires_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})} (hora argentina).</small>}</div>}{p.upcoming.length>0&&<p className="muted">Próximas etapas: {p.upcoming.join(" · ")}.</p>}{p.id==="premium"?<p className="muted">Servicio humano: alcance, dedicación y tiempos acordados con Amarango. Mayor personalización, mayor inversión.</p>:<p className="muted">Hasta {p.limit} productos.</p>}{onChoose&&<button disabled={disabled} onClick={()=>onChoose(p.id)}>{selected===p.id?"Nivel seleccionado":p.id==="tienda"?"Empezar gratis":p.id==="premium"?"Solicitar acompañamiento":`Solicitar ${p.name}`}</button>}</article>})}</div>
}
export async function changeStore(action:string,payload:unknown){
 const response=await fetch("/api/v16/stores",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload})});const data=await response.json();if(!response.ok)throw new Error(errorMessage(data.error));return data;
}
export function errorMessage(error:string){return ({forbidden:"Tu cuenta no tiene permiso para este cambio.",inactive:"La tienda necesita habilitación de Amarango.",locked:"Esta herramienta requiere otro nivel.",limit:"Llegaste al límite de productos del nivel.",slug_taken:"Ese enlace ya está usado. Elegí otro.",exists:"Tu cuenta ya tiene una tienda.",not_found:"No encontramos ese registro en tu tienda.",unauthenticated:"Ingresá con tu cuenta de ChatGPT para continuar.",invalid:"Revisá los campos antes de guardar."} as Record<string,string>)[error]??"No se pudo guardar. Tus datos siguen en el formulario."}
