"use client";
import { AppSelect } from "@/components/ui/app-select";
import {useState} from "react";
import {PLANS,type PlanId,type PlanPrice,type ToolValue} from "@/lib/subscriptions/plans";
const optionalNumber=(value:FormDataEntryValue|null)=>value==null||value===""?null:Number(value);
export function PlanValueEditor({plan,price,disabled,onSave}:{plan:Exclude<PlanId,"tienda">;price?:PlanPrice;disabled:boolean;onSave:(payload:unknown)=>Promise<void>}){
 const [currency,setCurrency]=useState<"USD"|"ARS">(price?.price_currency??"USD");
 const p=PLANS.find(p=>p.id===plan)!;
 const [tools,setTools]=useState<ToolValue[]>(price?.tool_values?.length?price.tool_values:p.features.filter(f=>!f.startsWith("Todo lo")).map(name=>({name,reference_price:null,promo_price:null})));
 function update(index:number,key:keyof ToolValue,value:string){setTools(tools.map((t,i)=>i===index?{...t,[key]:key==="name"?value:value===""?null:Number(value)}:t))}
 return <form className="owner-value-editor" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const expiry=String(f.get("expiry")??"");await onSave({id:plan,price_currency:currency,monthly_price:optionalNumber(f.get("monthly")),setup_price:optionalNumber(f.get("setup")),previous_price:optionalNumber(f.get("previous")),promo_price:optionalNumber(f.get("promo")),promo_text:String(f.get("text")??""),promo_expires_at:expiry?new Date(`${expiry}:00-03:00`).toISOString():null,tool_values:tools})}}>
  <h3>{p.name}</h3><p className="muted">Dólares como valor de referencia; pesos calculados con la cotización de Propietarios. Cambiar la moneda conserva los números: revisalos antes de guardar. Vacío significa “A definir”. El valor total del nivel se configura por separado del valor de sus herramientas.</p>
  <label>Moneda de los valores<AppSelect value={currency} onChange={e=>setCurrency(e.target.value as "USD"|"ARS")}><option value="USD">Dólares (USD)</option><option value="ARS">Pesos (ARS)</option></AppSelect></label><div className="store-fields"><label>{plan==="premium"?`Acompañamiento mensual (${currency})`:`Precio total mensual del nivel (${currency})`}<input type="number" name="monthly" min="0" max="10000000" step="0.01" defaultValue={price?.monthly_price??""} placeholder="A definir"/></label><label>{plan==="premium"?`Implementación personalizada (${currency})`:`Alta (${currency})`}<input type="number" name="setup" min="0" max="10000000" step="0.01" defaultValue={price?.setup_price??""} placeholder="A definir"/></label><label>Precio anterior para mostrar tachado ({currency})<input type="number" name="previous" min="0" max="10000000" step="0.01" defaultValue={price?.previous_price??""} placeholder="Opcional"/></label><label>Precio promocional mensual ({currency})<input type="number" name="promo" min="0" max="10000000" step="0.01" defaultValue={price?.promo_price??""} placeholder="Opcional"/></label><label>Texto de promoción<input name="text" maxLength={220} defaultValue={price?.promo_text??""} placeholder="Opcional"/></label><label>Vigencia hasta (hora argentina)<input type="datetime-local" name="expiry" defaultValue={price?.promo_expires_at?new Date(Date.parse(price.promo_expires_at)-3*60*60*1000).toISOString().slice(0,16):""}/></label></div>
  <h4>{plan==="premium"?"Valor estimado de cada servicio":"Herramientas y valor individual de referencia"}</h4><div className="owner-tool-list">{tools.map((t,i)=><fieldset className="owner-tool-value" key={i}><legend>Herramienta {i+1}</legend><label>Nombre<input required maxLength={120} value={t.name} onChange={e=>update(i,"name",e.target.value)}/></label><label>Valor de referencia ({currency})<input type="number" min="0" max="10000000" step="0.01" placeholder="A definir" value={t.reference_price??""} onChange={e=>update(i,"reference_price",e.target.value)}/></label><label>Promo individual ({currency})<input type="number" min="0" max="10000000" step="0.01" placeholder="Opcional" value={t.promo_price??""} onChange={e=>update(i,"promo_price",e.target.value)}/></label><button type="button" disabled={disabled} onClick={()=>setTools(tools.filter((_,n)=>n!==i))}>Quitar herramienta {i+1}</button></fieldset>)}</div><div className="store-toolbar"><button type="button" disabled={disabled||tools.length>=16} onClick={()=>setTools([...tools,{name:"",reference_price:null,promo_price:null}])}>Agregar herramienta</button><button className="primary" disabled={disabled}>Guardar valores de {p.name}</button></div><p className="muted">Las promociones deben ser menores que su valor de referencia. Guardar valores no genera cobros ni habilita niveles.</p>
 </form>
}
