"use client";
import {useState} from "react";
import {PLANS,planMoney,planARS,money,type PlanId,type PlanPrice,type CommercialRequest} from "@/lib/subscriptions/plans";
import {planValue} from "@/lib/subscriptions/guidance";
export function PlanRequestPreview({plan,price}:{plan:PlanId;price?:PlanPrice}){
 const p=PLANS.find(p=>p.id===plan)!,v=planValue(price),ars=planARS(v.current,price);
 return <div className="private-offer-summary"><h3>{p.name}</h3>{plan==="tienda"?<p><b>Gratis</b> · Empezá sin inversión inicial.</p>:<><p>Mensual: <b>{v.current==null?"A definir":planMoney(v.current,price)}</b>{price?.price_currency==="USD"&&<small>{ars==null?"Equivalente en pesos: a definir":`Equivalente: ARS ${money(ars)}`}</small>}</p><p>{plan==="premium"?"Implementación personalizada":"Alta"}: <b>{price?.setup_price==null?"A definir":planMoney(price.setup_price,price)}</b></p>{price?.price_currency==="USD"&&<small>Cotización: {price.usd_to_ars==null?"A definir":`1 USD = ARS ${money(price.usd_to_ars)}`} {price.fx_updated_at&&`· Actualizada ${new Date(price.fx_updated_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})}`}</small>}{v.promotionActive&&price?.promo_expires_at&&<p>Promoción hasta {new Date(price.promo_expires_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})} (hora argentina).</p>}</>}<ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul>{plan==="premium"&&<p>El alcance, las horas y el seguimiento del servicio uno a uno se acuerdan en privado.</p>}<p className="muted">El importe final y las condiciones se confirman en privado con Amarango. Esta solicitud no genera cobros ni habilita herramientas.</p></div>
}
export function PrivatePlanRequest({plan,price,busy,onCancel,onConfirm}:{plan:PlanId;price?:PlanPrice;busy:boolean;onCancel:()=>void;onConfirm:(payload:unknown)=>Promise<boolean>}){
 return <section className="store-panel" id="private-plan-request"><h2>Prepará tu solicitud</h2><PlanRequestPreview plan={plan} price={price}/><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const ok=await onConfirm({requested_plan:plan,contact_phone:String(f.get("contact_phone")??""),message:String(f.get("message")??""),...(price?.updated_at?{offer_updated_at:price.updated_at,fx_updated_at:price.fx_updated_at??null}:{})});if(ok)onCancel()}}><RequestContactFields/><label className="check"><input type="checkbox" required/>Revisé el nivel y solicito coordinar el cierre en privado. Propietarios debe autorizar la habilitación.</label><div className="store-toolbar"><button className="primary" disabled={busy}>Enviar solicitud para cerrar en privado</button><button type="button" disabled={busy} onClick={onCancel}>Ahora no</button></div></form></section>
}
export function RequestContactFields(){return <div className="store-fields"><label>WhatsApp o teléfono para coordinar<input name="contact_phone" type="tel" maxLength={30} pattern="[+0-9 ()-]*" placeholder="Opcional, con código de país"/></label><label>¿Qué querés resolver con este nivel?<textarea name="message" maxLength={1000} placeholder="Opcional: contanos tu prioridad"/></label></div>}
export function commercialSummary(r:CommercialRequest){const name=PLANS.find(p=>p.id===r.plan)?.name;return [`Solicitud AmarangoElectro · ${r.id}`,`Negocio: ${r.business}`,`Nivel: ${name}`,`Mensual: ${r.monthly==null?"A definir":planMoney(r.monthly,r.offer)}`,`Equivalente mensual en pesos: ${r.monthly_ars==null?"A definir":`ARS ${money(r.monthly_ars)}`}`,`Alta / implementación: ${r.setup==null?"A definir":planMoney(r.setup,r.offer)}`,`Equivalente de alta en pesos: ${r.setup_ars==null?"A definir":`ARS ${money(r.setup_ars)}`}`,`Cotización USD/ARS: ${r.offer.usd_to_ars??"A definir"}`,`Preparada: ${r.created_at}`,r.offer.promo_expires_at?`Vigencia de promoción: ${r.offer.promo_expires_at}`:"",...(r.offer.tool_values??[]).map(t=>`${t.name}: ${t.reference_price==null?"A definir":planMoney(t.reference_price,r.offer)}${t.promo_price!=null&&(!r.offer.promo_expires_at||Date.parse(r.offer.promo_expires_at)>Date.parse(r.created_at))?` · Promo ${planMoney(t.promo_price,r.offer)}`:""}`),r.contact_phone?`Contacto: ${r.contact_phone}`:"",r.message?`Prioridad: ${r.message}`:"",`Incluye: ${PLANS.find(p=>p.id===r.plan)?.features.join("; ")}`,"Pendiente de confirmación privada y autorización de Propietarios. La app no cobra."].filter(Boolean).join("\n")}
export function CommercialRequestCard({request:r}:{request:CommercialRequest}){const [feedback,setFeedback]=useState("");return <div className="commercial-request-card"><h3>Solicitud preparada · cierre privado</h3><p>{r.business} · {PLANS.find(p=>p.id===r.plan)?.name}</p><p>Mensual: <b>{r.monthly==null?"A definir":planMoney(r.monthly,r.offer)}</b>{r.offer.price_currency==="USD"&&<small>{r.monthly_ars==null?"Equivalente en pesos: a definir":`Equivalente: ARS ${money(r.monthly_ars)}`}</small>}</p><p>Alta / implementación: {r.setup==null?"A definir":planMoney(r.setup,r.offer)}</p>{r.contact_phone&&<p>Contacto: {r.contact_phone}</p>}{r.message&&<p>Prioridad: {r.message}</p>}<small>Valores guardados al solicitar, {new Date(r.created_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})}. Confirmación comercial en privado; habilitación por Propietarios.</small><details><summary>Ver resumen completo</summary><pre>{commercialSummary(r)}</pre></details><button onClick={async()=>{try{await navigator.clipboard.writeText(commercialSummary(r));setFeedback("Resumen copiado para compartir en privado.")}catch{setFeedback("Abrí el resumen completo para copiarlo manualmente.")}}}>Copiar resumen para cierre privado</button><p role="status">{feedback}</p></div>}
