"use client";
import {useEffect,useState,type FormEvent} from "react";
import {PLANS,canUse,money,installmentQuote,assetUrl,type StoreData,type StoreProduct,type PlanId} from "@/lib/subscriptions/plans";
import {PlanCards,changeStore,errorMessage} from "./plan-cards";
import {StorePhotoEditor} from "./store-photo-editor";
import {createPhoto} from "@/lib/photo-intelligence/browser-flyer";
import {parseSpecificationLines} from "@/lib/photo-intelligence/flyer-text";
type Tab="catalog"|"brand"|"calculator"|"crm"|"sales";
const tabs:[Tab,string][]=[["catalog","Catálogo"],["brand","Logo y colores"],["calculator","Calculadora"],["crm","Clientes"],["sales","Ventas"]];
export function StoreWorkspace(){
 const [data,setData]=useState<StoreData|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState<Tab>("catalog"),[plan,setPlan]=useState<PlanId>("tienda"),[product,setProduct]=useState<StoreProduct|null>(null),[editing,setEditing]=useState(false),[selected,setSelected]=useState<string[]>([]),[photos,setPhotos]=useState<StoreProduct[]>([]);
 const [customerId,setCustomerId]=useState(""),[saleProduct,setSaleProduct]=useState(""),[saleId,setSaleId]=useState<string|null>(null);
 const [cash,setCash]=useState(0),[count,setCount]=useState(2);
 async function refresh(){const response=await fetch("/api/v16/stores",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(errorMessage(value.error));setData(value)}
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[]);
 async function perform(action:string,payload:unknown,success="Cambios guardados."){setBusy(true);setMessage("");try{await changeStore(action,payload);await refresh();setMessage(success);return true}catch(e){setMessage(e instanceof Error?e.message:"No se pudo guardar.");return false}finally{setBusy(false)}}
 if(error)return <main className="subscriber-workspace"><p role="alert">{error}</p><button onClick={()=>{setError("");void refresh().catch(e=>setError(e.message))}}>Reintentar</button></main>;
 if(!data)return <main className="subscriber-workspace"><p role="status">Cargando tu espacio…</p></main>;
 const store=data.store;
 if(!store)return <main className="subscriber-workspace"><section className="subscription-intro"><small>TU TIENDA, PASO A PASO</small><h1>Tu tienda gratis. Crecé a tu ritmo.</h1><p>Empezá con catálogo, contado, logo, colores y fotos propias sin pagar. Solicitá herramientas adicionales cuando las necesites; Amarango autoriza cada cambio de nivel.</p></section><PlanCards prices={data.plans} selected={plan} onChoose={setPlan}/><form className="store-panel" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await perform("create",{name:f.get("name"),slug:f.get("slug"),requested_plan:plan,consent:true},"Solicitud creada.")}}><h2>Crear mi tienda gratis</h2><div className="store-fields"><label>Nombre de tu negocio<input required name="name" minLength={2} maxLength={80}/></label><label>Nombre para el enlace<input required name="slug" pattern="[a-z0-9][a-z0-9-]{2,49}" placeholder="mi-negocio" maxLength={50}/><small>Letras minúsculas, números y guiones. Ejemplo: /tienda/mi-negocio</small></label></div><label className="check"><input type="checkbox" required/>Solicito mi tienda base gratis. Amarango debe habilitar el acceso privado y los cambios de nivel. Las herramientas pagas están a definir; esta solicitud no genera un cobro.</label><button className="primary" disabled={busy}>{plan==="tienda"?"Solicitar mi tienda gratis":"Crear tienda gratis y solicitar el nivel elegido"}</button><p role="status">{message}</p></form><p>La vista sigue privada. Equipos, cobranzas y automatizaciones adicionales se incorporarán por etapas.</p></main>;
 const active=store.status==="active",currentPlan=PLANS.find(p=>p.id===store.plan)!;
 const locked=(tab==="calculator"&&!canUse(store.plan,"calculator"))||((tab==="crm"||tab==="sales")&&!canUse(store.plan,"crm"));
 const quote=store.financing[String(count)]!=null&&cash>0?installmentQuote(cash,count,store.financing[String(count)]):null;
 async function productSave(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await perform("product",{id:product?.id??crypto.randomUUID(),name:f.get("name"),cash_price:Number(f.get("cash_price")),visible:f.get("visible")==="on",features:String(f.get("features")??"").split("\n").map(x=>x.trim()).filter(Boolean),specifications:parseSpecificationLines(String(f.get("specs")??""))})){setEditing(false);setProduct(null)}}
 async function logo(file?:File){if(!file)return;setBusy(true);setMessage("Guardando logo…");try{if(file.size>12000000||!/^image\/(png|jpeg|webp)$/.test(file.type))throw new Error("Usá PNG, JPG o WebP de hasta 12 MB.");const src=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});const jpeg=await createPhoto(src,store!.name,"original");const form=new FormData();form.set("image",await(await fetch(jpeg)).blob(),"logo.jpg");form.set("metadata",JSON.stringify({kind:"logo",reviewed:true}));const r=await fetch("/api/v16/store-upload",{method:"POST",body:form});const v=await r.json();if(!r.ok)throw new Error(errorMessage(v.error));await refresh();setMessage("Logo guardado.")}catch(e){setMessage(e instanceof Error?e.message:"No se guardó el logo.")}finally{setBusy(false)}}
 return <main className="subscriber-workspace"><header className="subscription-intro"><small>MI NEGOCIO · {currentPlan.name.toUpperCase()}</small><h1>{store.name}</h1><p>{active?`${data.products.length} de ${currentPlan.limit} productos · Herramientas del nivel ${currentPlan.name}`:store.status==="pending"?"Tu solicitud está pendiente de habilitación por Amarango.":"Tu tienda está pausada. Contactá a Amarango para reactivarla."}</p>{active&&store.published&&<a href={`/tienda/${store.slug}`}>Abrir mi tienda →</a>}</header><p className="store-message" role="status">{message}</p>{active&&store.plan==="premium"&&<section className="store-panel"><h2>Tu acompañamiento uno a uno</h2><p>Coordiná con Amarango el diagnóstico del negocio, la configuración, el catálogo, la estrategia de ventas y la adaptación de herramientas. El alcance, las horas de dedicación y los tiempos se acuerdan de forma personalizada.</p></section>}{active&&<><nav className="store-tabs" aria-label="Herramientas de mi tienda">{tabs.map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setMessage("")}}>{label}{((id==="crm"||id==="sales")&&!canUse(store.plan,"crm"))||(id==="calculator"&&!canUse(store.plan,"calculator"))?" 🔒":""}</button>)}</nav>{locked?<section className="store-panel"><h2>{tab==="calculator"?"Calculadora · desde Cuotas":"Clientes y ventas · nivel Gestión"}</h2><p>Sumá esta herramienta cuando tu negocio la necesite. La solicitud no cambia tu nivel hasta que Amarango lo habilite.</p><button disabled={busy} onClick={()=>void perform("request_plan",{requested_plan:tab==="calculator"?"cuotas":"gestion"},"Solicitud enviada a Propietarios.")}>Solicitar habilitación</button></section>:<>
 {tab==="catalog"&&<><div className="store-toolbar"><button className="primary" disabled={busy} onClick={()=>{setProduct(null);setEditing(true)}}>Agregar producto</button>{canUse(store.plan,"flyers")&&<button disabled={busy||!selected.length} onClick={()=>setPhotos(data.products.filter(p=>selected.includes(p.id)))}>Fotos con mi marca ({selected.length})</button>}</div>{editing&&<form className="store-panel" key={product?.id??"new"} onSubmit={e=>void productSave(e)}><h2>{product?"Editar producto":"Nuevo producto"}</h2><div className="store-fields"><label>Nombre<input name="name" required defaultValue={product?.name} maxLength={150} minLength={2}/></label><label>Precio de contado ($)<input name="cash_price" type="number" required min="0.01" max="100000000" step="0.01" defaultValue={product?.cash_price}/></label><label>Características (una por línea)<textarea name="features" rows={3} maxLength={2700} defaultValue={product?.features.join("\n")}/></label><label>Especificaciones (Nombre: Valor)<textarea name="specs" rows={3} maxLength={7000} defaultValue={Object.entries(product?.specifications??{}).map(([k,v])=>`${k}: ${v}`).join("\n")}/></label></div><label className="check"><input name="visible" type="checkbox" defaultChecked={product?.visible??true}/>Visible en mi tienda</label><button className="primary" disabled={busy}>Guardar producto</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancelar</button><p className="muted">Guardá el producto y después elegí “Cambiar foto” en su tarjeta.</p></form>}
 <div className="store-product-grid">{data.products.map(p=><article className="store-product-card" key={p.id}>{canUse(store.plan,"flyers")&&<label className="check"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/>Seleccionar</label>}{p.asset_id?<img src={assetUrl(store.id,p.asset_id)} alt={p.name}/>:<div className="empty-photo">Agregá la foto de este producto</div>}<h3>{p.name}</h3><strong>{money(p.cash_price)}</strong><small>{p.visible?"Visible":"Oculto"}</small><button disabled={busy} onClick={()=>{setProduct(p);setEditing(true)}}>Editar datos y precio</button><button disabled={busy} onClick={()=>setPhotos([p])}>Cambiar foto</button></article>)}</div>{!data.products.length&&<p>Tu catálogo está vacío. Agregá tu primer producto con su precio de contado.</p>}</>}
 {tab==="brand"&&<section className="store-panel"><h2>Logo, colores y contacto</h2><div className="store-logo-preview">{store.logo_asset_id?<img src={assetUrl(store.id,store.logo_asset_id)} alt={`Logo de ${store.name}`}/>:<span>Tu logo</span>}<label>Cambiar mi logo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{void logo(e.target.files?.[0]);e.target.value=""}}/></label></div><form key={store.name+store.primary_color+store.accent_color} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await perform("brand",{name:f.get("name"),primary_color:f.get("primary"),accent_color:f.get("accent"),whatsapp:f.get("whatsapp"),published:f.get("published")==="on"})}}><div className="store-fields"><label>Nombre<input name="name" required minLength={2} maxLength={80} defaultValue={store.name}/></label><label>WhatsApp con código de país<input name="whatsapp" inputMode="numeric" pattern="[0-9]{0,18}" maxLength={18} placeholder="54911…" defaultValue={store.whatsapp}/></label><label>Color principal<input name="primary" type="color" defaultValue={store.primary_color}/></label><label>Color de acento<input name="accent" type="color" defaultValue={store.accent_color}/></label></div><label className="check"><input name="published" type="checkbox" defaultChecked={store.published}/>Mostrar mi catálogo en /tienda/{store.slug}</label><p className="muted">El enlace sigue la disponibilidad del sitio Amarango. Actualmente la vista está privada.</p><button className="primary" disabled={busy}>Guardar identidad</button></form></section>}
 {tab==="calculator"&&<section className="store-panel"><h2>Calculadora comercial AmarangoElectro</h2><p>Calculá sobre tus precios de contado con los recargos de tu negocio. Estas cifras no son cotizaciones de la financiera Amarango.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await perform("financing",{financing:{"2":Number(f.get("2")),"4":Number(f.get("4")),"6":Number(f.get("6"))}})}}><div className="store-fields">{[2,4,6].map(n=><label key={n}>Recargo total para {n} cuotas (%)<input name={String(n)} required type="number" min="0" max="300" step="0.01" defaultValue={store.financing[String(n)]??""}/></label>)}</div><button disabled={busy}>Guardar reglas de mi negocio</button></form><div className="store-fields"><label>Precio de contado ($)<input type="number" min="0" value={cash||""} onChange={e=>setCash(Number(e.target.value))}/></label><label>Cuotas<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[2,4,6].map(n=><option key={n}>{n}</option>)}</select></label></div>{quote?<p className="store-summary">Total {money(quote.total)} · {count} cuotas: {money(quote.each)}{quote.last!==quote.each?` (última ${money(quote.last)})`:""}</p>:<p>Guardá los recargos e ingresá un precio para calcular.</p>}</section>}
 {tab==="crm"&&<section className="store-panel"><h2>Clientes de mi negocio</h2><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await perform("customer",{id:crypto.randomUUID(),name:f.get("name"),phone:f.get("phone"),notes:f.get("notes")}))form.reset()}}><div className="store-fields"><label>Nombre<input required name="name" minLength={2} maxLength={120}/></label><label>Teléfono<input name="phone" pattern="[0-9]{0,18}" maxLength={18} inputMode="numeric"/></label><label>Notas<textarea name="notes" maxLength={1500} rows={2}/></label></div><button className="primary" disabled={busy}>Agregar cliente</button></form><div className="store-list">{data.customers.map(c=>{const sales=data.sales.filter(s=>s.customer_id===c.id);return <details key={c.id}><summary>{c.name} · {sales.length} ventas</summary><p>{c.phone||"Sin teléfono"}</p><p>{c.notes}</p>{sales.map(s=><p key={s.id}>{s.snapshot.product} · {money(s.total)} · {new Date(s.created_at).toLocaleDateString("es-AR")}</p>)}</details>})}</div></section>}
 {tab==="sales"&&<section className="store-panel"><h2>Ventas de contado</h2><p>Registro comercial de tu negocio. No registra un cobro bancario ni emite una factura.</p><p className="store-summary">{data.sales.length} ventas · Total registrado: {money(data.sales.reduce((sum,s)=>sum+Number(s.total),0))}</p><form onSubmit={async e=>{e.preventDefault();const id=saleId??crypto.randomUUID();setSaleId(id);if(await perform("sale",{id,customer_id:customerId,product_id:saleProduct},"Venta registrada en tu negocio.")){setSaleId(null);setCustomerId("");setSaleProduct("")}}}><div className="store-fields"><label>Cliente<select required value={customerId} onChange={e=>{setCustomerId(e.target.value);setSaleId(null)}}><option value="">Elegir cliente</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Producto<select required value={saleProduct} onChange={e=>{setSaleProduct(e.target.value);setSaleId(null)}}><option value="">Elegir producto</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.cash_price)}</option>)}</select></label></div><button className="primary" disabled={busy||!customerId||!saleProduct}>Registrar venta de contado</button></form><div className="store-list">{data.sales.map(s=><article key={s.id}><strong>{s.snapshot.customer}</strong><p>{s.snapshot.product} · {money(s.total)}</p><small>{new Date(s.created_at).toLocaleString("es-AR")}</small></article>)}</div></section>}
 </>}</>}
 <details className="store-panel"><summary>Mi nivel y próximas herramientas</summary><p>Solicitado: {PLANS.find(p=>p.id===store.requested_plan)?.name}. Cambiar el nivel requiere habilitación de Amarango.</p><PlanCards prices={data.plans} selected={store.plan} disabled={busy} onChoose={id=>void perform("request_plan",{requested_plan:id},"Solicitud de nivel enviada.")}/><p>Tienda base gratis. Servicios pagos a definir y habilitados por Propietarios. Premium requiere acordar el acompañamiento uno a uno. Equipos, cobranzas y automatizaciones adicionales se incorporarán por etapas.</p></details>
 {!!photos.length&&<StorePhotoEditor store={store} products={photos} onClose={()=>setPhotos([])} onSaved={refresh}/>}</main>
}
