"use client";
import { AppSelect } from "@/components/ui/app-select";
import {useEffect,useState} from "react";
import {assetUrl,type Store,type StoreProduct,canUse} from "@/lib/subscriptions/plans";
import {readFlyer,createPhoto} from "@/lib/photo-intelligence/browser-flyer";
import {parseSpecificationLines} from "@/lib/photo-intelligence/flyer-text";
import {errorMessage} from "./plan-cards";
export function StorePhotoEditor({store,products,onClose,onSaved}:{store:Store;products:StoreProduct[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const [index,setIndex]=useState(0),[image,setImage]=useState<string|null>(null),[style,setStyle]=useState<"original"|"amarango">("original"),[features,setFeatures]=useState(products[0].features.join("\n")),[specs,setSpecs]=useState(Object.entries(products[0].specifications).map(([k,v])=>`${k}: ${v}`).join("\n")),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const p=products[index];const src=image??(p.source_asset_id?assetUrl(store.id,p.source_asset_id):p.asset_id?assetUrl(store.id,p.asset_id):null);
 const [preview,setPreview]=useState<string|null>(null);
 useEffect(()=>{let alive=true;setPreview(null);if(src&&style==="amarango"){void createPhoto(src,p.name,style,{name:store.name,primary:store.primary_color,accent:store.accent_color,logo:store.logo_asset_id?assetUrl(store.id,store.logo_asset_id):undefined}).then(photo=>{if(alive)setPreview(photo)}).catch(()=>{if(alive)setMessage("Para ver el marco, subí la foto original desde tu dispositivo.")})}return()=>{alive=false}},[src,style,p.name,store.id,store.name,store.primary_color,store.accent_color,store.logo_asset_id]);
 function move(next:number){setIndex(next);setImage(null);setFeatures(products[next].features.join("\n"));setSpecs(Object.entries(products[next].specifications).map(([k,v])=>`${k}: ${v}`).join("\n"));setReview(false);setStyle("original");setMessage("")}
 async function read(src:string){setBusy(true);setReview(false);try{const facts=await readFlyer(src,setMessage);setFeatures(facts.features.join("\n"));setSpecs(Object.entries(facts.specifications).map(([k,v])=>`${k}: ${v}`).join("\n"));setMessage("Lectura lista. Revisá los datos antes de guardar.")}catch{setMessage("No pudimos leer la foto. Podés escribir los datos manualmente.")}finally{setBusy(false)}}
 async function choose(file?:File){if(!file)return;if(file.size>12000000||!/^image\/(jpeg|png|webp)$/.test(file.type)){setMessage("Usá JPG, PNG o WebP de hasta 12 MB.");return}const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject();r.readAsDataURL(file)});setImage(data);setFeatures("");setSpecs("");setReview(false);if(canUse(store.plan,"flyers"))await read(data)}
 async function save(){if(!src||!review)return;setBusy(true);setMessage("Guardando foto…");try{
  const brand={name:store.name,primary:store.primary_color,accent:store.accent_color,logo:store.logo_asset_id?assetUrl(store.id,store.logo_asset_id):undefined};
  const main=await createPhoto(src,p.name,style,brand),source=await createPhoto(src,p.name,"original");
  const form=new FormData();form.set("image",await(await fetch(main)).blob(),"foto.jpg");form.set("sourceImage",await(await fetch(source)).blob(),"original.jpg");
  form.set("metadata",JSON.stringify({kind:"product",product_id:p.id,features:features.split("\n").map(x=>x.trim()).filter(Boolean),specifications:parseSpecificationLines(specs),reviewed:true}));
  const response=await fetch("/api/v16/store-upload",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(errorMessage(data.error));await onSaved();setMessage("Foto guardada en tu tienda.");setReview(false);
 }catch(e){setMessage(e instanceof Error?e.message:"No se guardó la foto.")}finally{setBusy(false)}}
 return <div className="store-modal-overlay"><section className="store-photo-modal" role="dialog" aria-modal="true" aria-label="Foto de producto"><header><div><small>FOTO {index+1} DE {products.length}</small><h2>{p.name}</h2></div><button disabled={busy} onClick={onClose}>Cerrar</button></header>{src&&<img className="photo-source" src={preview??src} alt={preview?"Vista previa con logo y colores de tu tienda":"Foto de proveedor completa"}/>}<label>1. Elegí la foto de este producto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void choose(e.target.files?.[0]).catch(()=>setMessage("No se pudo abrir la foto."));e.target.value=""}}/></label>{canUse(store.plan,"flyers")&&<><label>2. Estilo<AppSelect value={style} disabled={busy} onChange={e=>{setStyle(e.target.value as typeof style);setReview(false)}}><option value="original">Foto original</option><option value="amarango">Marco con logo y colores de mi tienda</option></AppSelect></label><button disabled={busy||!src} onClick={()=>src&&void read(src)}>Leer características de la foto</button></>}<label>Características (una por línea)<textarea value={features} onChange={e=>{setFeatures(e.target.value);setReview(false)}} rows={4} maxLength={2700}/></label><label>Especificaciones (Nombre: Valor)<textarea value={specs} onChange={e=>{setSpecs(e.target.value);setReview(false)}} rows={4} maxLength={7000}/></label><label className="check"><input type="checkbox" checked={review} disabled={busy} onChange={e=>setReview(e.target.checked)}/>Revisé que la foto y los datos correspondan a este producto.</label><p role="status">{message}</p><button className="primary" disabled={busy||!review||!src} onClick={()=>void save()}>Guardar foto y características</button>{products.length>1&&<nav><button disabled={busy||index===0} onClick={()=>move(index-1)}>Anterior</button><button disabled={busy||index===products.length-1} onClick={()=>move(index+1)}>Siguiente producto</button></nav>}</section></div>
}
