'use client';
import {useState} from 'react';
import {Dialog} from 'radix-ui';
import {commercialCommission,type CommissionModality} from '@/lib/advisor-compensation/commercial-policy';
const money=(n:number)=>`$${n.toLocaleString('es-AR',{maximumFractionDigits:2})}`;
export function CommissionProductGain({name,price,cap,modality='cash'}:{name:string;price:number|null;cap:number|null|undefined;modality?:CommissionModality}){
 const [selected,setSelected]=useState<CommissionModality>(modality),[count,setCount]=useState(6);
 const available=typeof price==='number'&&Number.isFinite(price)&&price>0&&cap!==undefined;
 const preview=available?commercialCommission(price!,modality,6,cap!):null;
 const detail=available?commercialCommission(price!,selected,count,cap!):null;
 return <Dialog.Root onOpenChange={open=>{if(open)setSelected(modality)}}><Dialog.Trigger asChild><button type="button" className="commission-gain">Ganás {preview?money(preview.amount):'A confirmar'}<small> Nueva escala estimada · pendiente de habilitación</small></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="amarango-dialog-overlay"/><Dialog.Content className="amarango-reason-dialog"><small>COMISIÓN ESTIMADA</small><Dialog.Title>{name}</Dialog.Title><Dialog.Description>Vista previa de la nueva escala. Su aplicación a nuevas ventas está pendiente de habilitación por Propietarios. Las ventas confirmadas conservan su comisión registrada.</Dialog.Description><div className="product-calculator-options" role="group" aria-label="Modalidad de comisión"><button aria-pressed={selected==='cash'} onClick={()=>setSelected('cash')}>Contado</button><button aria-pressed={selected==='financed'} onClick={()=>setSelected('financed')}>Financiado</button></div>{selected==='financed'&&<div className="product-calculator-options" role="group" aria-label="Plan para pagos de comisión"><button aria-pressed={count===3} onClick={()=>setCount(3)}>3 cuotas · 2 pagos</button><button aria-pressed={count===6} onClick={()=>setCount(6)}>6 cuotas · 3 pagos</button></div>}<dl className="commission-detail"><div><dt>Precio de venta contado</dt><dd>{available?money(price!):'A confirmar'}</dd></div><div><dt>Comisión</dt><dd>{detail?money(detail.amount):'A confirmar'}</dd></div><div><dt>Modalidad</dt><dd>{selected==='cash'?'Contado':'Financiado'}</dd></div></dl>{detail&&<p>{detail.payments.length} pago{detail.payments.length>1?'s':''}: {detail.payments.map(money).join(' + ')}</p>}<p>La comisión cobrada depende de los pagos registrados. El premio mensual se valida por ventas equivalentes. El tope desde $300.000 está a definir por Propietarios.</p><div className="amarango-reason-actions"><Dialog.Close>Volver</Dialog.Close></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
