import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const resolvePackage=createRequire(import.meta.url);
const root=new URL('../',import.meta.url);
async function load(path,state){globalThis.__subscriberTest=state;const result=await build({entryPoints:[new URL(path,root).pathname],bundle:true,write:false,format:'esm',platform:'node',jsx:'automatic',plugins:[{name:'trusted-boundaries',setup(b){
 b.onResolve({filter:/^(?:react(?:\/|$)|lucide-react$)/},args=>({path:pathToFileURL(resolvePackage.resolve(args.path)).href,external:true}));
 b.onResolve({filter:/^@\//},args=>args.path.includes('chatgpt-auth')||args.path.includes('lib/server/backend')?{path:args.path,namespace:'mock'}:{path:new URL(args.path.slice(2)+'.ts',root).pathname});
 b.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:args.path.includes('chatgpt-auth')?'export async function getChatGPTUser(){return globalThis.__subscriberTest.user}':`export async function backendFetch(path,init){const s=globalThis.__subscriberTest;s.calls.push({path,init});return s.respond(path,init)};export function sameOrigin(r){return (!r.headers.get('origin')||r.headers.get('origin')===new URL(r.url).origin)&&r.headers.get('sec-fetch-site')!=='cross-site'};export function privateJson(body,status=200){return Response.json(body,{status})}`}));
 }}]});return import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64')+'#'+Math.random())}
const initial=()=>({user:{id:'trusted-site-account',email:'trusted@example.invalid'},calls:[],respond:()=>Response.json({ok:true})});
const req=(action,payload,headers={})=>new Request('https://site.test/api/v16/stores',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify({action,payload})});
const product={id:'d3e8da0f-5b6a-46fc-81b8-8c355a8799c3',name:'Product',cash_price:1000.01,visible:true,features:[],specifications:{}};
test('missing stable identity cannot reach privileged store RPC',async()=>{const s=initial();s.user.id=null;const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.GET(new Request('https://site.test/api/v16/stores'))).status,401);assert.equal(s.calls.length,0)});
test('cross-origin mutation is rejected before database access',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('product',product,{origin:'https://other.test'}))).status,403);assert.equal(s.calls.length,0)});
test('client cannot inject a tenant or identity into a product mutation',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);for(const extra of [{store_id:'other-store'},{p_user_id:'other-user'},{owner:true}])assert.equal((await route.POST(req('product',{...product,...extra}))).status,400);assert.equal(s.calls.length,0)});
test('server uses only trusted Sites identity and forwards validated action',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('product',product))).status,200);const call=JSON.parse(s.calls[0].init.body);assert.equal(call.p_user_id,s.user.id);assert.equal(call.p_email,s.user.email);assert.equal(call.p_action,'product');assert.deepEqual(call.p_payload,product)});
test('owner registry denial stays denied with an admin query parameter',async()=>{const s=initial();s.respond=()=>Response.json({error:'forbidden'});const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.GET(new Request('https://site.test/api/v16/stores?view=owner'))).status,403);assert.equal(JSON.parse(s.calls[0].init.body).p_action,'owner_list')});
test('signup requires explicit consent and cannot submit active status or plan',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);const payload={name:'My Shop',slug:'my-shop',requested_plan:'gestion',consent:true};assert.equal((await route.POST(req('create',{...payload,status:'active'}))).status,400);assert.equal((await route.POST(req('create',{...payload,plan:'gestion'}))).status,400);assert.equal((await route.POST(req('create',{...payload,consent:false}))).status,400);assert.equal(s.calls.length,0)});
test('sales reject client prices, and rates reject non-finite or excessive values',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('sale',{id:product.id,customer_id:product.id,product_id:product.id,total:1}))).status,400);assert.equal((await route.POST(req('financing',{financing:{'2':-1,'4':55,'6':78}}))).status,400);assert.equal((await route.POST(req('financing',{financing:{'2':15,'4':55,'6':301}}))).status,400);assert.equal(s.calls.length,0)});
test('paused tenant cannot upload or write metadata',async()=>{const s=initial();s.respond=()=>Response.json({store:{id:product.id,status:'paused'},products:[]});const route=await load('app/api/v16/store-upload/route.ts',s);const form=new FormData();form.set('metadata',JSON.stringify({kind:'logo',reviewed:true}));form.set('image',new Blob([new Uint8Array([255,216,255,0])],{type:'image/jpeg'}),'logo.jpg');assert.equal((await route.POST(new Request('https://site.test/api/v16/store-upload',{method:'POST',body:form}))).status,403);assert.equal(s.calls.length,1)});
test('logo upload is one write and publishes metadata only after upload success',async()=>{const s=initial();s.respond=(path)=>path.includes('/rpc/')?Response.json(s.calls.length===1?{store:{id:product.id,status:'active'},products:[]}:{ok:true}):new Response(null,{status:201});const route=await load('app/api/v16/store-upload/route.ts',s);const form=new FormData();form.set('metadata',JSON.stringify({kind:'logo',reviewed:true}));form.set('image',new Blob([new Uint8Array([255,216,255,0])],{type:'image/jpeg'}),'logo.jpg');assert.equal((await route.POST(new Request('https://site.test/api/v16/store-upload',{method:'POST',body:form}))).status,200);assert.equal(s.calls.filter(x=>x.path.includes('/storage/')).length,1);assert.match(s.calls[1].path,new RegExp('/'+product.id+'/'));assert.equal(JSON.parse(s.calls[2].init.body).p_action,'asset')});
test('failed upload never makes the asset visible in tenant metadata',async()=>{const s=initial();s.respond=(path)=>path.includes('/rpc/')?Response.json({store:{id:product.id,status:'active'},products:[]}):new Response(null,{status:503});const route=await load('app/api/v16/store-upload/route.ts',s);const form=new FormData();form.set('metadata',JSON.stringify({kind:'logo',reviewed:true}));form.set('image',new Blob([new Uint8Array([255,216,255,0])],{type:'image/jpeg'}),'logo.jpg');assert.equal((await route.POST(new Request('https://site.test/api/v16/store-upload',{method:'POST',body:form}))).status,503);assert.equal(s.calls.length,2)});
test('public store lookup restricts slug and uses a private-field-safe database projection',async()=>{const s=initial();const {publicStore}=await load('lib/subscriptions/server.ts',s);assert.equal(await publicStore('../../owner-registry'),null);assert.equal(s.calls.length,0);await publicStore('my-shop');assert.equal(s.calls[0].path,'/rest/v1/rpc/v16_public_store');assert.deepEqual(JSON.parse(s.calls[0].init.body),{p_slug:'my-shop'})});
test('subscription calculator reconciles final cents without duplicating initial installments',async()=>{const {installmentQuote,canUse}=await load('lib/subscriptions/plans.ts',initial());const q=installmentQuote(391999,2,15);assert.equal(Math.round((q.each+q.last)*100),Math.round(q.total*100));assert.equal(canUse('tienda','crm'),false);assert.equal(canUse('cuotas','crm'),false);assert.equal(canUse('gestion','crm'),true);assert.equal(canUse('premium','crm'),true);assert.equal(canUse('premium','calculator'),true)});

test('free foundation cannot receive a paid monthly fee through the owners API',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('owner_price',{id:'tienda',monthly_price:5000,setup_price:0}))).status,400);assert.equal(s.calls.length,0)});
test('Premium is a request and retains trusted identity instead of self-activation',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('request_plan',{requested_plan:'premium'}))).status,200);const call=JSON.parse(s.calls[0].init.body);assert.equal(call.p_action,'request_plan');assert.deepEqual(call.p_payload,{requested_plan:'premium'});assert.equal(call.p_user_id,s.user.id)});
test('Premium paid values remain editable without creating a payment',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('owner_price',{id:'premium',monthly_price:null,setup_price:null}))).status,200);assert.equal(s.calls.length,1);assert.equal(JSON.parse(s.calls[0].init.body).p_action,'owner_price')});
test('commercial cards promise free entry and distinguish personal support from upcoming modules',async()=>{const {PlanCards}=await load('components/subscriptions/plan-cards.tsx',initial());const {renderToStaticMarkup}=await import('react-dom/server');const html=renderToStaticMarkup(PlanCards({prices:[{id:'tienda',monthly_price:9999,setup_price:9999}]}));assert.match(html,/Tienda gratis/);assert.match(html,/>Gratis</);assert.match(html,/Sin cuota mensual ni costo de alta/);assert.doesNotMatch(html,/9[.,]999/);assert.match(html,/Premium 1 a 1/);assert.match(html,/Servicio humano/);assert.match(html,/Próximas etapas/);assert.ok((html.match(/>A definir</g)||[]).length>=3)});

const diagnosis={need:'financing',tools:['installments'],monthly_sales:'starting',installments:'want',budget:null,value:'simplicity'};
test('diagnosis and growth actions cannot carry tenant IDs, activate levels or set prices',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);for(const [action,payload] of [['diagnosis',{diagnosis,store_id:product.id}],['diagnosis',{diagnosis:{...diagnosis,plan:'premium'}}],['growth_interest',{need:'financing',plan:'cuotas'}],['dismiss_suggestion',{key:'volume',store_id:product.id}]])assert.equal((await route.POST(req(action,payload))).status,400);assert.equal(s.calls.length,0);assert.equal((await route.POST(req('diagnosis',{diagnosis}))).status,200);assert.deepEqual(JSON.parse(s.calls[0].init.body).p_payload,{diagnosis})});
test('owners pricing rejects artificial discounts and malformed reference values',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);const base={id:'gestion',monthly_price:100,setup_price:null};for(const extra of [{promo_price:150},{promo_price:1,monthly_price:null},{previous_price:50},{tool_values:[{name:'CRM',reference_price:null,promo_price:10}]},{tool_values:[{name:'CRM',reference_price:10,promo_price:20}]},{promo_expires_at:'not-a-date'}])assert.equal((await route.POST(req('owner_price',{...base,...extra}))).status,400);assert.equal(s.calls.length,0);assert.equal((await route.POST(req('owner_price',{...base,previous_price:120,promo_price:80,tool_values:[{name:'CRM',reference_price:100,promo_price:70}],promo_text:'Promotion',promo_expires_at:'2099-01-01T00:00:00Z'}))).status,200)});
test('six-question recommendations cover every level and respect free-entry choice',async()=>{const {recommend}=await load('lib/subscriptions/guidance.ts',initial());const base={...diagnosis,need:'sales',tools:['store','brand'],installments:'no'};assert.equal(recommend(base).plan,'tienda');assert.equal(recommend(diagnosis).plan,'cuotas');assert.equal(recommend({...base,tools:['crm']}).plan,'gestion');assert.equal(recommend({...base,monthly_sales:'over_100'}).plan,'gestion');assert.equal(recommend({...base,value:'support'}).plan,'premium');assert.equal(recommend({...diagnosis,need:'support',budget:0}).plan,'tienda');assert.match(recommend(diagnosis).budgetNote,/a definir/);assert.match(recommend({...diagnosis,budget:50},[{id:'cuotas',monthly_price:100,setup_price:null}]).budgetNote,/supera el presupuesto/)});
test('expired promos revert to configured values and incomplete totals stay undefined',async()=>{const {planValue}=await load('lib/subscriptions/guidance.ts',initial());const price={id:'gestion',monthly_price:100,setup_price:null,previous_price:120,promo_price:80,promo_expires_at:'2026-10-01T00:00:00Z',tool_values:[{name:'CRM',reference_price:100,promo_price:60}]};assert.equal(planValue(price,Date.parse('2026-09-01')).current,80);assert.equal(planValue(price,Date.parse('2026-10-02')).current,100);assert.equal(planValue(price,Date.parse('2026-10-02')).previous,null);assert.equal(planValue({...price,tool_values:[{name:'CRM',reference_price:null,promo_price:null}]}).referenceTotal,null);assert.equal(planValue({...price,tool_values:[{name:'CRM',reference_price:0.1,promo_price:null},{name:'Calculator',reference_price:0.2,promo_price:null}]}).referenceTotal,0.3)});
test('growth hints use own usage and needs, dismiss persistently and never mutate the plan',async()=>{const {growthSuggestion}=await load('lib/subscriptions/guidance.ts',initial());const data={store:{plan:'tienda',requested_plan:'tienda',status:'active',growth_interests:[],growth_dismissed:[]},products:[],sales:[],customers:[],plans:[],usage:{customers:0,monthly_sales:0}};assert.equal(growthSuggestion(data),null);let a={...data,store:{...data.store,growth_interests:['financing']}};assert.equal(growthSuggestion(a).plan,'cuotas');assert.equal(a.store.plan,'tienda');assert.equal(growthSuggestion({...a,store:{...a.store,growth_dismissed:['financing']}}),null);assert.equal(growthSuggestion({...data,usage:{customers:30,monthly_sales:0}}).plan,'gestion');assert.equal(growthSuggestion({...a,store:{...a.store,status:'paused'}}),null);assert.equal(growthSuggestion({...a,store:{...a.store,requested_plan:'cuotas'}}),null);assert.equal(growthSuggestion({...data,store:{...data.store,plan:'premium'},usage:{customers:100,monthly_sales:100}}),null)});
test('plan cards render configured discounts, no free strike-through and optional diagnosis entry',async()=>{const {PlanCards}=await load('components/subscriptions/plan-cards.tsx',initial());const {renderToStaticMarkup}=await import('react-dom/server');const html=renderToStaticMarkup(PlanCards({prices:[{id:'gestion',monthly_price:100,setup_price:null,promo_price:80,previous_price:120,tool_values:[{name:'CRM propio',reference_price:100,promo_price:60}],promo_text:'Own configured promo'}]}));assert.match(html,/<del>/);assert.match(html,/Own configured promo/);assert.match(html,/Valor de las herramientas/);const {BusinessDiagnosis}=await load('components/subscriptions/business-diagnosis.tsx',initial());const el=renderToStaticMarkup((await import('react')).createElement(BusinessDiagnosis,{prices:[],onComplete:async()=>true,onChoose:()=>{},onCompare:()=>{}}));assert.match(el,/Orientarme en 6 pasos/);assert.match(el,/Comparar todos los niveles/)});
