import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
async function load(path,state){globalThis.__subscriberTest=state;const result=await build({entryPoints:[new URL(path,root).pathname],bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'trusted-boundaries',setup(b){
 b.onResolve({filter:/^@\//},args=>args.path.includes('chatgpt-auth')||args.path.includes('lib/server/backend')?{path:args.path,namespace:'mock'}:{path:new URL(args.path.slice(2)+'.ts',root).pathname});
 b.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:args.path.includes('chatgpt-auth')?'export async function getChatGPTUser(){return globalThis.__subscriberTest.user}':`export async function backendFetch(path,init){const s=globalThis.__subscriberTest;s.calls.push({path,init});return s.respond(path,init)};export function sameOrigin(r){return (!r.headers.get('origin')||r.headers.get('origin')===new URL(r.url).origin)&&r.headers.get('sec-fetch-site')!=='cross-site'};export function privateJson(body,status=200){return Response.json(body,{status})}`}));
 }}]});return import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64')+'#'+Math.random())}
const initial=()=>({user:{id:'trusted-site-account',email:'trusted@example.invalid'},calls:[],respond:()=>Response.json({ok:true})});
const req=(action,payload,headers={})=>new Request('https://site.test/api/v16/stores',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify({action,payload})});
const product={id:'d3e8da0f-5b6a-46fc-81b8-8c355a8799c3',name:'Product',cash_price:1000.01,visible:true,features:[],specifications:{}};
test('missing stable identity cannot reach privileged store RPC',async()=>{const s=initial();s.user.id=null;const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.GET(new Request('https://site.test/api/v16/stores'))).status,401);assert.equal(s.calls.length,0)});
test('cross-origin mutation is rejected before database access',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('product',product,{origin:'https://other.test'}))).status,403);assert.equal(s.calls.length,0)});
test('client cannot inject a tenant or identity into a product mutation',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);for(const extra of [{store_id:'other-store'},{p_user_id:'other-user'},{owner:true}])assert.equal((await route.POST(req('product',{...product,...extra}))).status,400);assert.equal(s.calls.length,0)});
test('server uses only trusted Sites identity and forwards validated action',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('product',product))).status,200);const call=JSON.parse(s.calls[0].init.body);assert.equal(call.p_user_id,s.user.id);assert.equal(call.p_email,s.user.email);assert.equal(call.p_action,'product');assert.deepEqual(call.p_payload,product)});
test('owner registry denial stays denied with an admin query parameter',async()=>{const s=initial();s.respond=()=>Response.json({error:'forbidden'});const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.GET(new Request('https://site.test/api/v16/stores?view=owner'))).status,403);assert.equal(JSON.parse(s.calls[0].init.body).p_action,'owner_list')});
test('signup requires explicit consent and cannot submit active status or plan',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);const payload={name:'My Shop',slug:'my-shop',requested_plan:'gestion',consent:true};assert.equal((await route.POST(req('create',{...payload,status:'active'}))).status,400);assert.equal((await route.POST(req('create',{...payload,plan:'gestion'}))).status,400);assert.equal((await route.POST(req('create',{...payload,consent:false}))).status,400);assert.equal(s.calls.length,0)});
test('sales reject client prices, and rates reject non-finite or excessive values',async()=>{const s=initial();const route=await load('app/api/v16/stores/route.ts',s);assert.equal((await route.POST(req('sale',{id:product.id,customer_id:product.id,product_id:product.id,total:1}))).status,400);assert.equal((await route.POST(req('financing',{financing:{'2':-1,'4':55,'6':78}}))).status,400);assert.equal((await route.POST(req('financing',{financing:{'2':15,'4':55,'6':301}}))).status,400);assert.equal(s.calls.length,0)});
test('paused tenant cannot upload or write metadata',async()=>{const s=initial();s.respond=()=>Response.json({store:{id:product.id,status:'paused'},products:[]});const route=await load('app/api/v16/store-upload/route.ts',s);const form=new FormData();form.set('metadata',JSON.stringify({kind:'logo',reviewed:true}));form.set('image',new Blob([new Uint8Array([255,216,255,0])],{type:'image/jpeg'}),'logo.jpg');assert.equal((await route.POST(new Request('https://site.test/api/v16/store-upload',{method:'POST',body:form}))).status,403);assert.equal(s.calls.length,1)});
test('logo upload is one write and publishes metadata only after upload success',async()=>{const s=initial();s.respond=(path)=>path.includes('/rpc/')?Response.json(s.calls.length===1?{store:{id:product.id,status:'active'},products:[]}:{ok:true}):new Response(null,{status:201});const route=await load('app/api/v16/store-upload/route.ts',s);const form=new FormData();form.set('metadata',JSON.stringify({kind:'logo',reviewed:true}));form.set('image',new Blob([new Uint8Array([255,216,255,0])],{type:'image/jpeg'}),'logo.jpg');assert.equal((await route.POST(new Request('https://site.test/api/v16/store-upload',{method:'POST',body:form}))).status,200);assert.equal(s.calls.filter(x=>x.path.includes('/storage/')).length,1);assert.match(s.calls[1].path,new RegExp('/'+product.id+'/'));assert.equal(JSON.parse(s.calls[2].init.body).p_action,'asset')});
test('failed upload never makes the asset visible in tenant metadata',async()=>{const s=initial();s.respond=(path)=>path.includes('/rpc/')?Response.json({store:{id:product.id,status:'active'},products:[]}):new Response(null,{status:503});const route=await load('app/api/v16/store-upload/route.ts',s);const form=new FormData();form.set('metadata',JSON.stringify({kind:'logo',reviewed:true}));form.set('image',new Blob([new Uint8Array([255,216,255,0])],{type:'image/jpeg'}),'logo.jpg');assert.equal((await route.POST(new Request('https://site.test/api/v16/store-upload',{method:'POST',body:form}))).status,503);assert.equal(s.calls.length,2)});
test('public store lookup restricts slug and uses a private-field-safe database projection',async()=>{const s=initial();const {publicStore}=await load('lib/subscriptions/server.ts',s);assert.equal(await publicStore('../../owner-registry'),null);assert.equal(s.calls.length,0);await publicStore('my-shop');assert.equal(s.calls[0].path,'/rest/v1/rpc/v16_public_store');assert.deepEqual(JSON.parse(s.calls[0].init.body),{p_slug:'my-shop'})});
test('subscription calculator reconciles final cents without duplicating initial installments',async()=>{const {installmentQuote,canUse}=await load('lib/subscriptions/plans.ts',initial());const q=installmentQuote(391999,2,15);assert.equal(Math.round((q.each+q.last)*100),Math.round(q.total*100));assert.equal(canUse('tienda','crm'),false);assert.equal(canUse('cuotas','crm'),false);assert.equal(canUse('gestion','crm'),true)});
