export const adminCenterFoundation = Object.freeze({
  publicRouteEnabled: false,
  productionWritesEnabled: false,
  supabaseWritesEnabled: false,
  requiresRealAuthBeforeActivation: true,
  requiresRlsBeforeActivation: true,
  requiresAdminMfaBeforeActivation: true,
  requiresAuditLogBeforeActivation: true,
  bulkImportRequiresPreview: true,
  ambiguousRowsRequireHumanReview: true,
  newProductsDefaultVisible: false,
  supplierVisibleToAdminOnly: true,
  costVisibleToAdminOnly: true,
  fxVisibleToAdminOnly: true,
  legacyAdminParityRequired: true,
  legacyPasteFormatsMustRemainCompatible: true,
  legacyFeatureRemovalRequiresOwnerApproval: true,
  screenshotParityLockRequired: true,
  adminUxMayReduceStepsButNotCapabilities: true,
  contextActionsMustRemainNearProduct: true,
  productEditorSingleSurfaceRequired: true,
  adminProductCardsRequired: true,
  adminCatalogMinimumScale: 1200,
  largeCatalogMustUseIncrementalRendering: true,
  amarangoCalculatorAdminOnlyRequired: true,
  platesSystemRequired: true,
});
